# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import gobgp_pb2 as gobgp__pb2


class GobgpApiStub(object):
  """Interface exported by the server.

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StartServer = channel.unary_unary(
        '/gobgpapi.GobgpApi/StartServer',
        request_serializer=gobgp__pb2.StartServerRequest.SerializeToString,
        response_deserializer=gobgp__pb2.StartServerResponse.FromString,
        )
    self.StopServer = channel.unary_unary(
        '/gobgpapi.GobgpApi/StopServer',
        request_serializer=gobgp__pb2.StopServerRequest.SerializeToString,
        response_deserializer=gobgp__pb2.StopServerResponse.FromString,
        )
    self.GetServer = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetServer',
        request_serializer=gobgp__pb2.GetServerRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetServerResponse.FromString,
        )
    self.AddNeighbor = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddNeighbor',
        request_serializer=gobgp__pb2.AddNeighborRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddNeighborResponse.FromString,
        )
    self.DeleteNeighbor = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeleteNeighbor',
        request_serializer=gobgp__pb2.DeleteNeighborRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeleteNeighborResponse.FromString,
        )
    self.GetNeighbor = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetNeighbor',
        request_serializer=gobgp__pb2.GetNeighborRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetNeighborResponse.FromString,
        )
    self.ResetNeighbor = channel.unary_unary(
        '/gobgpapi.GobgpApi/ResetNeighbor',
        request_serializer=gobgp__pb2.ResetNeighborRequest.SerializeToString,
        response_deserializer=gobgp__pb2.ResetNeighborResponse.FromString,
        )
    self.SoftResetNeighbor = channel.unary_unary(
        '/gobgpapi.GobgpApi/SoftResetNeighbor',
        request_serializer=gobgp__pb2.SoftResetNeighborRequest.SerializeToString,
        response_deserializer=gobgp__pb2.SoftResetNeighborResponse.FromString,
        )
    self.ShutdownNeighbor = channel.unary_unary(
        '/gobgpapi.GobgpApi/ShutdownNeighbor',
        request_serializer=gobgp__pb2.ShutdownNeighborRequest.SerializeToString,
        response_deserializer=gobgp__pb2.ShutdownNeighborResponse.FromString,
        )
    self.EnableNeighbor = channel.unary_unary(
        '/gobgpapi.GobgpApi/EnableNeighbor',
        request_serializer=gobgp__pb2.EnableNeighborRequest.SerializeToString,
        response_deserializer=gobgp__pb2.EnableNeighborResponse.FromString,
        )
    self.DisableNeighbor = channel.unary_unary(
        '/gobgpapi.GobgpApi/DisableNeighbor',
        request_serializer=gobgp__pb2.DisableNeighborRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DisableNeighborResponse.FromString,
        )
    self.GetRib = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetRib',
        request_serializer=gobgp__pb2.GetRibRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetRibResponse.FromString,
        )
    self.ValidateRib = channel.unary_unary(
        '/gobgpapi.GobgpApi/ValidateRib',
        request_serializer=gobgp__pb2.ValidateRibRequest.SerializeToString,
        response_deserializer=gobgp__pb2.ValidateRibResponse.FromString,
        )
    self.AddPath = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddPath',
        request_serializer=gobgp__pb2.AddPathRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddPathResponse.FromString,
        )
    self.DeletePath = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeletePath',
        request_serializer=gobgp__pb2.DeletePathRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeletePathResponse.FromString,
        )
    self.MonitorRib = channel.unary_stream(
        '/gobgpapi.GobgpApi/MonitorRib',
        request_serializer=gobgp__pb2.MonitorRibRequest.SerializeToString,
        response_deserializer=gobgp__pb2.Destination.FromString,
        )
    self.MonitorPeerState = channel.unary_stream(
        '/gobgpapi.GobgpApi/MonitorPeerState',
        request_serializer=gobgp__pb2.Arguments.SerializeToString,
        response_deserializer=gobgp__pb2.Peer.FromString,
        )
    self.EnableMrt = channel.unary_unary(
        '/gobgpapi.GobgpApi/EnableMrt',
        request_serializer=gobgp__pb2.EnableMrtRequest.SerializeToString,
        response_deserializer=gobgp__pb2.EnableMrtResponse.FromString,
        )
    self.DisableMrt = channel.unary_unary(
        '/gobgpapi.GobgpApi/DisableMrt',
        request_serializer=gobgp__pb2.DisableMrtRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DisableMrtResponse.FromString,
        )
    self.InjectMrt = channel.stream_unary(
        '/gobgpapi.GobgpApi/InjectMrt',
        request_serializer=gobgp__pb2.InjectMrtRequest.SerializeToString,
        response_deserializer=gobgp__pb2.InjectMrtResponse.FromString,
        )
    self.AddBmp = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddBmp',
        request_serializer=gobgp__pb2.AddBmpRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddBmpResponse.FromString,
        )
    self.DeleteBmp = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeleteBmp',
        request_serializer=gobgp__pb2.DeleteBmpRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeleteBmpResponse.FromString,
        )
    self.GetRpki = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetRpki',
        request_serializer=gobgp__pb2.GetRpkiRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetRpkiResponse.FromString,
        )
    self.AddRpki = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddRpki',
        request_serializer=gobgp__pb2.AddRpkiRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddRpkiResponse.FromString,
        )
    self.DeleteRpki = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeleteRpki',
        request_serializer=gobgp__pb2.DeleteRpkiRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeleteRpkiResponse.FromString,
        )
    self.EnableRpki = channel.unary_unary(
        '/gobgpapi.GobgpApi/EnableRpki',
        request_serializer=gobgp__pb2.EnableRpkiRequest.SerializeToString,
        response_deserializer=gobgp__pb2.EnableRpkiResponse.FromString,
        )
    self.DisableRpki = channel.unary_unary(
        '/gobgpapi.GobgpApi/DisableRpki',
        request_serializer=gobgp__pb2.DisableRpkiRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DisableRpkiResponse.FromString,
        )
    self.ResetRpki = channel.unary_unary(
        '/gobgpapi.GobgpApi/ResetRpki',
        request_serializer=gobgp__pb2.ResetRpkiRequest.SerializeToString,
        response_deserializer=gobgp__pb2.ResetRpkiResponse.FromString,
        )
    self.SoftResetRpki = channel.unary_unary(
        '/gobgpapi.GobgpApi/SoftResetRpki',
        request_serializer=gobgp__pb2.SoftResetRpkiRequest.SerializeToString,
        response_deserializer=gobgp__pb2.SoftResetRpkiResponse.FromString,
        )
    self.GetRoa = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetRoa',
        request_serializer=gobgp__pb2.GetRoaRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetRoaResponse.FromString,
        )
    self.EnableZebra = channel.unary_unary(
        '/gobgpapi.GobgpApi/EnableZebra',
        request_serializer=gobgp__pb2.EnableZebraRequest.SerializeToString,
        response_deserializer=gobgp__pb2.EnableZebraResponse.FromString,
        )
    self.AddVrf = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddVrf',
        request_serializer=gobgp__pb2.AddVrfRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddVrfResponse.FromString,
        )
    self.DeleteVrf = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeleteVrf',
        request_serializer=gobgp__pb2.DeleteVrfRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeleteVrfResponse.FromString,
        )
    self.GetVrf = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetVrf',
        request_serializer=gobgp__pb2.GetVrfRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetVrfResponse.FromString,
        )
    self.GetDefinedSet = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetDefinedSet',
        request_serializer=gobgp__pb2.GetDefinedSetRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetDefinedSetResponse.FromString,
        )
    self.AddDefinedSet = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddDefinedSet',
        request_serializer=gobgp__pb2.AddDefinedSetRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddDefinedSetResponse.FromString,
        )
    self.DeleteDefinedSet = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeleteDefinedSet',
        request_serializer=gobgp__pb2.DeleteDefinedSetRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeleteDefinedSetResponse.FromString,
        )
    self.ReplaceDefinedSet = channel.unary_unary(
        '/gobgpapi.GobgpApi/ReplaceDefinedSet',
        request_serializer=gobgp__pb2.ReplaceDefinedSetRequest.SerializeToString,
        response_deserializer=gobgp__pb2.ReplaceDefinedSetResponse.FromString,
        )
    self.GetStatement = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetStatement',
        request_serializer=gobgp__pb2.GetStatementRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetStatementResponse.FromString,
        )
    self.AddStatement = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddStatement',
        request_serializer=gobgp__pb2.AddStatementRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddStatementResponse.FromString,
        )
    self.DeleteStatement = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeleteStatement',
        request_serializer=gobgp__pb2.DeleteStatementRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeleteStatementResponse.FromString,
        )
    self.ReplaceStatement = channel.unary_unary(
        '/gobgpapi.GobgpApi/ReplaceStatement',
        request_serializer=gobgp__pb2.ReplaceStatementRequest.SerializeToString,
        response_deserializer=gobgp__pb2.ReplaceStatementResponse.FromString,
        )
    self.GetPolicy = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetPolicy',
        request_serializer=gobgp__pb2.GetPolicyRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetPolicyResponse.FromString,
        )
    self.AddPolicy = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddPolicy',
        request_serializer=gobgp__pb2.AddPolicyRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddPolicyResponse.FromString,
        )
    self.DeletePolicy = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeletePolicy',
        request_serializer=gobgp__pb2.DeletePolicyRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeletePolicyResponse.FromString,
        )
    self.ReplacePolicy = channel.unary_unary(
        '/gobgpapi.GobgpApi/ReplacePolicy',
        request_serializer=gobgp__pb2.ReplacePolicyRequest.SerializeToString,
        response_deserializer=gobgp__pb2.ReplacePolicyResponse.FromString,
        )
    self.GetPolicyAssignment = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetPolicyAssignment',
        request_serializer=gobgp__pb2.GetPolicyAssignmentRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetPolicyAssignmentResponse.FromString,
        )
    self.AddPolicyAssignment = channel.unary_unary(
        '/gobgpapi.GobgpApi/AddPolicyAssignment',
        request_serializer=gobgp__pb2.AddPolicyAssignmentRequest.SerializeToString,
        response_deserializer=gobgp__pb2.AddPolicyAssignmentResponse.FromString,
        )
    self.DeletePolicyAssignment = channel.unary_unary(
        '/gobgpapi.GobgpApi/DeletePolicyAssignment',
        request_serializer=gobgp__pb2.DeletePolicyAssignmentRequest.SerializeToString,
        response_deserializer=gobgp__pb2.DeletePolicyAssignmentResponse.FromString,
        )
    self.ReplacePolicyAssignment = channel.unary_unary(
        '/gobgpapi.GobgpApi/ReplacePolicyAssignment',
        request_serializer=gobgp__pb2.ReplacePolicyAssignmentRequest.SerializeToString,
        response_deserializer=gobgp__pb2.ReplacePolicyAssignmentResponse.FromString,
        )
    self.GetRibInfo = channel.unary_unary(
        '/gobgpapi.GobgpApi/GetRibInfo',
        request_serializer=gobgp__pb2.GetRibInfoRequest.SerializeToString,
        response_deserializer=gobgp__pb2.GetRibInfoResponse.FromString,
        )


class GobgpApiServicer(object):
  """Interface exported by the server.

  """

  def StartServer(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopServer(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetServer(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddNeighbor(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteNeighbor(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNeighbor(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetNeighbor(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SoftResetNeighbor(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShutdownNeighbor(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnableNeighbor(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisableNeighbor(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRib(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateRib(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddPath(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePath(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MonitorRib(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MonitorPeerState(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnableMrt(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisableMrt(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InjectMrt(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddBmp(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBmp(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRpki(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddRpki(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRpki(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnableRpki(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisableRpki(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetRpki(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SoftResetRpki(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRoa(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnableZebra(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddVrf(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteVrf(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVrf(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDefinedSet(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddDefinedSet(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteDefinedSet(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplaceDefinedSet(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStatement(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddStatement(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteStatement(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplaceStatement(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPolicy(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddPolicy(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePolicy(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplacePolicy(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPolicyAssignment(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddPolicyAssignment(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePolicyAssignment(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplacePolicyAssignment(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRibInfo(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GobgpApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StartServer': grpc.unary_unary_rpc_method_handler(
          servicer.StartServer,
          request_deserializer=gobgp__pb2.StartServerRequest.FromString,
          response_serializer=gobgp__pb2.StartServerResponse.SerializeToString,
      ),
      'StopServer': grpc.unary_unary_rpc_method_handler(
          servicer.StopServer,
          request_deserializer=gobgp__pb2.StopServerRequest.FromString,
          response_serializer=gobgp__pb2.StopServerResponse.SerializeToString,
      ),
      'GetServer': grpc.unary_unary_rpc_method_handler(
          servicer.GetServer,
          request_deserializer=gobgp__pb2.GetServerRequest.FromString,
          response_serializer=gobgp__pb2.GetServerResponse.SerializeToString,
      ),
      'AddNeighbor': grpc.unary_unary_rpc_method_handler(
          servicer.AddNeighbor,
          request_deserializer=gobgp__pb2.AddNeighborRequest.FromString,
          response_serializer=gobgp__pb2.AddNeighborResponse.SerializeToString,
      ),
      'DeleteNeighbor': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteNeighbor,
          request_deserializer=gobgp__pb2.DeleteNeighborRequest.FromString,
          response_serializer=gobgp__pb2.DeleteNeighborResponse.SerializeToString,
      ),
      'GetNeighbor': grpc.unary_unary_rpc_method_handler(
          servicer.GetNeighbor,
          request_deserializer=gobgp__pb2.GetNeighborRequest.FromString,
          response_serializer=gobgp__pb2.GetNeighborResponse.SerializeToString,
      ),
      'ResetNeighbor': grpc.unary_unary_rpc_method_handler(
          servicer.ResetNeighbor,
          request_deserializer=gobgp__pb2.ResetNeighborRequest.FromString,
          response_serializer=gobgp__pb2.ResetNeighborResponse.SerializeToString,
      ),
      'SoftResetNeighbor': grpc.unary_unary_rpc_method_handler(
          servicer.SoftResetNeighbor,
          request_deserializer=gobgp__pb2.SoftResetNeighborRequest.FromString,
          response_serializer=gobgp__pb2.SoftResetNeighborResponse.SerializeToString,
      ),
      'ShutdownNeighbor': grpc.unary_unary_rpc_method_handler(
          servicer.ShutdownNeighbor,
          request_deserializer=gobgp__pb2.ShutdownNeighborRequest.FromString,
          response_serializer=gobgp__pb2.ShutdownNeighborResponse.SerializeToString,
      ),
      'EnableNeighbor': grpc.unary_unary_rpc_method_handler(
          servicer.EnableNeighbor,
          request_deserializer=gobgp__pb2.EnableNeighborRequest.FromString,
          response_serializer=gobgp__pb2.EnableNeighborResponse.SerializeToString,
      ),
      'DisableNeighbor': grpc.unary_unary_rpc_method_handler(
          servicer.DisableNeighbor,
          request_deserializer=gobgp__pb2.DisableNeighborRequest.FromString,
          response_serializer=gobgp__pb2.DisableNeighborResponse.SerializeToString,
      ),
      'GetRib': grpc.unary_unary_rpc_method_handler(
          servicer.GetRib,
          request_deserializer=gobgp__pb2.GetRibRequest.FromString,
          response_serializer=gobgp__pb2.GetRibResponse.SerializeToString,
      ),
      'ValidateRib': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateRib,
          request_deserializer=gobgp__pb2.ValidateRibRequest.FromString,
          response_serializer=gobgp__pb2.ValidateRibResponse.SerializeToString,
      ),
      'AddPath': grpc.unary_unary_rpc_method_handler(
          servicer.AddPath,
          request_deserializer=gobgp__pb2.AddPathRequest.FromString,
          response_serializer=gobgp__pb2.AddPathResponse.SerializeToString,
      ),
      'DeletePath': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePath,
          request_deserializer=gobgp__pb2.DeletePathRequest.FromString,
          response_serializer=gobgp__pb2.DeletePathResponse.SerializeToString,
      ),
      'MonitorRib': grpc.unary_stream_rpc_method_handler(
          servicer.MonitorRib,
          request_deserializer=gobgp__pb2.MonitorRibRequest.FromString,
          response_serializer=gobgp__pb2.Destination.SerializeToString,
      ),
      'MonitorPeerState': grpc.unary_stream_rpc_method_handler(
          servicer.MonitorPeerState,
          request_deserializer=gobgp__pb2.Arguments.FromString,
          response_serializer=gobgp__pb2.Peer.SerializeToString,
      ),
      'EnableMrt': grpc.unary_unary_rpc_method_handler(
          servicer.EnableMrt,
          request_deserializer=gobgp__pb2.EnableMrtRequest.FromString,
          response_serializer=gobgp__pb2.EnableMrtResponse.SerializeToString,
      ),
      'DisableMrt': grpc.unary_unary_rpc_method_handler(
          servicer.DisableMrt,
          request_deserializer=gobgp__pb2.DisableMrtRequest.FromString,
          response_serializer=gobgp__pb2.DisableMrtResponse.SerializeToString,
      ),
      'InjectMrt': grpc.stream_unary_rpc_method_handler(
          servicer.InjectMrt,
          request_deserializer=gobgp__pb2.InjectMrtRequest.FromString,
          response_serializer=gobgp__pb2.InjectMrtResponse.SerializeToString,
      ),
      'AddBmp': grpc.unary_unary_rpc_method_handler(
          servicer.AddBmp,
          request_deserializer=gobgp__pb2.AddBmpRequest.FromString,
          response_serializer=gobgp__pb2.AddBmpResponse.SerializeToString,
      ),
      'DeleteBmp': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBmp,
          request_deserializer=gobgp__pb2.DeleteBmpRequest.FromString,
          response_serializer=gobgp__pb2.DeleteBmpResponse.SerializeToString,
      ),
      'GetRpki': grpc.unary_unary_rpc_method_handler(
          servicer.GetRpki,
          request_deserializer=gobgp__pb2.GetRpkiRequest.FromString,
          response_serializer=gobgp__pb2.GetRpkiResponse.SerializeToString,
      ),
      'AddRpki': grpc.unary_unary_rpc_method_handler(
          servicer.AddRpki,
          request_deserializer=gobgp__pb2.AddRpkiRequest.FromString,
          response_serializer=gobgp__pb2.AddRpkiResponse.SerializeToString,
      ),
      'DeleteRpki': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRpki,
          request_deserializer=gobgp__pb2.DeleteRpkiRequest.FromString,
          response_serializer=gobgp__pb2.DeleteRpkiResponse.SerializeToString,
      ),
      'EnableRpki': grpc.unary_unary_rpc_method_handler(
          servicer.EnableRpki,
          request_deserializer=gobgp__pb2.EnableRpkiRequest.FromString,
          response_serializer=gobgp__pb2.EnableRpkiResponse.SerializeToString,
      ),
      'DisableRpki': grpc.unary_unary_rpc_method_handler(
          servicer.DisableRpki,
          request_deserializer=gobgp__pb2.DisableRpkiRequest.FromString,
          response_serializer=gobgp__pb2.DisableRpkiResponse.SerializeToString,
      ),
      'ResetRpki': grpc.unary_unary_rpc_method_handler(
          servicer.ResetRpki,
          request_deserializer=gobgp__pb2.ResetRpkiRequest.FromString,
          response_serializer=gobgp__pb2.ResetRpkiResponse.SerializeToString,
      ),
      'SoftResetRpki': grpc.unary_unary_rpc_method_handler(
          servicer.SoftResetRpki,
          request_deserializer=gobgp__pb2.SoftResetRpkiRequest.FromString,
          response_serializer=gobgp__pb2.SoftResetRpkiResponse.SerializeToString,
      ),
      'GetRoa': grpc.unary_unary_rpc_method_handler(
          servicer.GetRoa,
          request_deserializer=gobgp__pb2.GetRoaRequest.FromString,
          response_serializer=gobgp__pb2.GetRoaResponse.SerializeToString,
      ),
      'EnableZebra': grpc.unary_unary_rpc_method_handler(
          servicer.EnableZebra,
          request_deserializer=gobgp__pb2.EnableZebraRequest.FromString,
          response_serializer=gobgp__pb2.EnableZebraResponse.SerializeToString,
      ),
      'AddVrf': grpc.unary_unary_rpc_method_handler(
          servicer.AddVrf,
          request_deserializer=gobgp__pb2.AddVrfRequest.FromString,
          response_serializer=gobgp__pb2.AddVrfResponse.SerializeToString,
      ),
      'DeleteVrf': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteVrf,
          request_deserializer=gobgp__pb2.DeleteVrfRequest.FromString,
          response_serializer=gobgp__pb2.DeleteVrfResponse.SerializeToString,
      ),
      'GetVrf': grpc.unary_unary_rpc_method_handler(
          servicer.GetVrf,
          request_deserializer=gobgp__pb2.GetVrfRequest.FromString,
          response_serializer=gobgp__pb2.GetVrfResponse.SerializeToString,
      ),
      'GetDefinedSet': grpc.unary_unary_rpc_method_handler(
          servicer.GetDefinedSet,
          request_deserializer=gobgp__pb2.GetDefinedSetRequest.FromString,
          response_serializer=gobgp__pb2.GetDefinedSetResponse.SerializeToString,
      ),
      'AddDefinedSet': grpc.unary_unary_rpc_method_handler(
          servicer.AddDefinedSet,
          request_deserializer=gobgp__pb2.AddDefinedSetRequest.FromString,
          response_serializer=gobgp__pb2.AddDefinedSetResponse.SerializeToString,
      ),
      'DeleteDefinedSet': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteDefinedSet,
          request_deserializer=gobgp__pb2.DeleteDefinedSetRequest.FromString,
          response_serializer=gobgp__pb2.DeleteDefinedSetResponse.SerializeToString,
      ),
      'ReplaceDefinedSet': grpc.unary_unary_rpc_method_handler(
          servicer.ReplaceDefinedSet,
          request_deserializer=gobgp__pb2.ReplaceDefinedSetRequest.FromString,
          response_serializer=gobgp__pb2.ReplaceDefinedSetResponse.SerializeToString,
      ),
      'GetStatement': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatement,
          request_deserializer=gobgp__pb2.GetStatementRequest.FromString,
          response_serializer=gobgp__pb2.GetStatementResponse.SerializeToString,
      ),
      'AddStatement': grpc.unary_unary_rpc_method_handler(
          servicer.AddStatement,
          request_deserializer=gobgp__pb2.AddStatementRequest.FromString,
          response_serializer=gobgp__pb2.AddStatementResponse.SerializeToString,
      ),
      'DeleteStatement': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteStatement,
          request_deserializer=gobgp__pb2.DeleteStatementRequest.FromString,
          response_serializer=gobgp__pb2.DeleteStatementResponse.SerializeToString,
      ),
      'ReplaceStatement': grpc.unary_unary_rpc_method_handler(
          servicer.ReplaceStatement,
          request_deserializer=gobgp__pb2.ReplaceStatementRequest.FromString,
          response_serializer=gobgp__pb2.ReplaceStatementResponse.SerializeToString,
      ),
      'GetPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.GetPolicy,
          request_deserializer=gobgp__pb2.GetPolicyRequest.FromString,
          response_serializer=gobgp__pb2.GetPolicyResponse.SerializeToString,
      ),
      'AddPolicy': grpc.unary_unary_rpc_method_handler(
          servicer.AddPolicy,
          request_deserializer=gobgp__pb2.AddPolicyRequest.FromString,
          response_serializer=gobgp__pb2.AddPolicyResponse.SerializeToString,
      ),
      'DeletePolicy': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePolicy,
          request_deserializer=gobgp__pb2.DeletePolicyRequest.FromString,
          response_serializer=gobgp__pb2.DeletePolicyResponse.SerializeToString,
      ),
      'ReplacePolicy': grpc.unary_unary_rpc_method_handler(
          servicer.ReplacePolicy,
          request_deserializer=gobgp__pb2.ReplacePolicyRequest.FromString,
          response_serializer=gobgp__pb2.ReplacePolicyResponse.SerializeToString,
      ),
      'GetPolicyAssignment': grpc.unary_unary_rpc_method_handler(
          servicer.GetPolicyAssignment,
          request_deserializer=gobgp__pb2.GetPolicyAssignmentRequest.FromString,
          response_serializer=gobgp__pb2.GetPolicyAssignmentResponse.SerializeToString,
      ),
      'AddPolicyAssignment': grpc.unary_unary_rpc_method_handler(
          servicer.AddPolicyAssignment,
          request_deserializer=gobgp__pb2.AddPolicyAssignmentRequest.FromString,
          response_serializer=gobgp__pb2.AddPolicyAssignmentResponse.SerializeToString,
      ),
      'DeletePolicyAssignment': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePolicyAssignment,
          request_deserializer=gobgp__pb2.DeletePolicyAssignmentRequest.FromString,
          response_serializer=gobgp__pb2.DeletePolicyAssignmentResponse.SerializeToString,
      ),
      'ReplacePolicyAssignment': grpc.unary_unary_rpc_method_handler(
          servicer.ReplacePolicyAssignment,
          request_deserializer=gobgp__pb2.ReplacePolicyAssignmentRequest.FromString,
          response_serializer=gobgp__pb2.ReplacePolicyAssignmentResponse.SerializeToString,
      ),
      'GetRibInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetRibInfo,
          request_deserializer=gobgp__pb2.GetRibInfoRequest.FromString,
          response_serializer=gobgp__pb2.GetRibInfoResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gobgpapi.GobgpApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
